
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: "C:\Users\saraa\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"https://altshulerdev.api.crm4.dynamics.com" /generateActions /out:"C:\Users\saraa\source\repos\Main\Altshuler\Shared\DataModel\Crm\Alt.DataModel.Crm\EBG\Actions.cs" /namespace:"Alt.DataModel.Crm.Entities" /SuppressGeneratedCodeAttribute /codecustomization:"DLaB.CrmSvcUtilExtensions.Action.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Action.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Action.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"saraa@altshul.co.il" /password:"*********" 
//------------------------------------------------------------------------------

namespace Alt.DataModel.Crm.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/alt/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("alt_TemplateGenerator")]
	public partial class alt_TemplateGeneratorRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public int TemplateType
		{
			get
			{
				if (this.Parameters.Contains("TemplateType"))
				{
					return ((int)(this.Parameters["TemplateType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["TemplateType"] = value;
			}
		}
		
		public string TemplateId
		{
			get
			{
				if (this.Parameters.Contains("TemplateId"))
				{
					return ((string)(this.Parameters["TemplateId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["TemplateId"] = value;
			}
		}
		
		public string RegardingObjectName
		{
			get
			{
				if (this.Parameters.Contains("RegardingObjectName"))
				{
					return ((string)(this.Parameters["RegardingObjectName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RegardingObjectName"] = value;
			}
		}
		
		public string RegardingObjectId
		{
			get
			{
				if (this.Parameters.Contains("RegardingObjectId"))
				{
					return ((string)(this.Parameters["RegardingObjectId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RegardingObjectId"] = value;
			}
		}
		
		public alt_TemplateGeneratorRequest()
		{
			this.RequestName = "alt_TemplateGenerator";
			this.TemplateType = default(int);
			this.TemplateId = default(string);
			this.RegardingObjectName = default(string);
			this.RegardingObjectId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/alt/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("alt_TemplateGenerator")]
	public partial class alt_TemplateGeneratorResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public alt_TemplateGeneratorResponse()
		{
		}
		
		public string DescriptionMessage
		{
			get
			{
				if (this.Results.Contains("DescriptionMessage"))
				{
					return ((string)(this.Results["DescriptionMessage"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public bool IsSucceeded
		{
			get
			{
				if (this.Results.Contains("IsSucceeded"))
				{
					return ((bool)(this.Results["IsSucceeded"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
		
		public string SubjectTemplateMessage
		{
			get
			{
				if (this.Results.Contains("SubjectTemplateMessage"))
				{
					return ((string)(this.Results["SubjectTemplateMessage"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/alt/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("alt_Logger")]
	public partial class alt_LoggerRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public int Depth
		{
			get
			{
				if (this.Parameters.Contains("Depth"))
				{
					return ((int)(this.Parameters["Depth"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["Depth"] = value;
			}
		}
		
		public int OperationDuration
		{
			get
			{
				if (this.Parameters.Contains("OperationDuration"))
				{
					return ((int)(this.Parameters["OperationDuration"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["OperationDuration"] = value;
			}
		}
		
		public int MessageLevelCode
		{
			get
			{
				if (this.Parameters.Contains("MessageLevelCode"))
				{
					return ((int)(this.Parameters["MessageLevelCode"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["MessageLevelCode"] = value;
			}
		}
		
		public string MessageBlock
		{
			get
			{
				if (this.Parameters.Contains("MessageBlock"))
				{
					return ((string)(this.Parameters["MessageBlock"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["MessageBlock"] = value;
			}
		}
		
		public int EntryPointTypeCode
		{
			get
			{
				if (this.Parameters.Contains("EntryPointTypeCode"))
				{
					return ((int)(this.Parameters["EntryPointTypeCode"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["EntryPointTypeCode"] = value;
			}
		}
		
		public System.DateTime OverrideCreatedOn
		{
			get
			{
				if (this.Parameters.Contains("OverrideCreatedOn"))
				{
					return ((System.DateTime)(this.Parameters["OverrideCreatedOn"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Parameters["OverrideCreatedOn"] = value;
			}
		}
		
		public string Name
		{
			get
			{
				if (this.Parameters.Contains("Name"))
				{
					return ((string)(this.Parameters["Name"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Name"] = value;
			}
		}
		
		public string ExecutingSystemUserId
		{
			get
			{
				if (this.Parameters.Contains("ExecutingSystemUserId"))
				{
					return ((string)(this.Parameters["ExecutingSystemUserId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ExecutingSystemUserId"] = value;
			}
		}
		
		public string RequestId
		{
			get
			{
				if (this.Parameters.Contains("RequestId"))
				{
					return ((string)(this.Parameters["RequestId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RequestId"] = value;
			}
		}
		
		public string CorrelationId
		{
			get
			{
				if (this.Parameters.Contains("CorrelationId"))
				{
					return ((string)(this.Parameters["CorrelationId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CorrelationId"] = value;
			}
		}
		
		public int PerformanceExecutionDuration
		{
			get
			{
				if (this.Parameters.Contains("PerformanceExecutionDuration"))
				{
					return ((int)(this.Parameters["PerformanceExecutionDuration"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["PerformanceExecutionDuration"] = value;
			}
		}
		
		public string TargetLogicalName
		{
			get
			{
				if (this.Parameters.Contains("TargetLogicalName"))
				{
					return ((string)(this.Parameters["TargetLogicalName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["TargetLogicalName"] = value;
			}
		}
		
		public string TargetId
		{
			get
			{
				if (this.Parameters.Contains("TargetId"))
				{
					return ((string)(this.Parameters["TargetId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["TargetId"] = value;
			}
		}
		
		public alt_LoggerRequest()
		{
			this.RequestName = "alt_Logger";
			this.Depth = default(int);
			this.OperationDuration = default(int);
			this.MessageLevelCode = default(int);
			this.MessageBlock = default(string);
			this.EntryPointTypeCode = default(int);
			this.OverrideCreatedOn = default(System.DateTime);
			this.Name = default(string);
			this.ExecutingSystemUserId = default(string);
			this.RequestId = default(string);
			this.CorrelationId = default(string);
			this.PerformanceExecutionDuration = default(int);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/alt/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("alt_Logger")]
	public partial class alt_LoggerResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public alt_LoggerResponse()
		{
		}
	}
}
